services:
  app:
    build: .
    volumes:
      - uploads:/app/public/uploads
    environment:
      - MONGODB_URI=mongodb://root:Be9KfQnULhttaXi@mongo:27017/sonysauto?authSource=admin
      - NODE_ENV=production
    ports:
      - "8000:3000"
    env_file:
      - .env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Be9KfQnULhttaXi
    volumes:
      - mongo-data:/data/db
    networks:
      - default

volumes:
  uploads:
  mongo-data:
