services:
  app:
    container_name: sonysauto_staging
    build: .
    volumes:
      - uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
    ports:
      - "3003:3000"
    env_file:
      - .env
    networks:
      - dokploy-network

volumes:
  uploads:

networks:
  dokploy-network:
    external: true
